#!/bin/bash

sudo apt-get install libboost-all-dev
sudo apt-get install gperf
sudo apt-get install libuuid1
sudo apt-get install uuid-dev

# 1.2 branch - latest - unstable
#wget https://launchpad.net/gearmand/1.2/1.1.11/+download/gearmand-1.1.11.tar.gz

# 1.0 branch - older - stable
wget https://launchpad.net/gearmand/1.0/1.0.6/+download/gearmand-1.0.6.tar.gz 

tar xf gearmand-1.*.tar.gz
cd gearmand-1.*

./configure
make
sudo make install

cd -

