#!/bin/bash

export PGPASSWORD=
export PGUSER=
export DBNAME=
DUMP=$1

PSQL=sudo -u postgres /usr/local/pgsql/bin/psql -a -c
PCTL=sudo -u postgres /usr/local/pgsql/bin/pg_ctl -D /usr/local/pgsql/data -l  /tmp/logfile

# Kill all open sessions
$PCTL start

# Re create DB
$PSQL "DROP DATABASE $DBNAME"
$PSQL "CREATE DATABASE $DBNAME"

# Import all the shit
$PSQL -d $DBNAME -f $DUMP 2> import_error.log

