#!/bin/bash
environment=development
join=.
prefix=gearman.worker
gid=apache
uid=apache

workers='appointment.appointment
appointment.appointment_due_reminder
appointment.appointment_reminder
appointment.appointment_sms_reminder
appointment.appointment_status_change
appointment.appointment_visit_reminder
ehr.ehr_document
ehr.ehr_share_info
library.library_document_share
office.office_creation
patient.patient_new_conversation
patient.patient_visit_medicament_made
patient.patient_visit_next_visit_reminder
patient.patient_visit_next_visit_sms_reminder
staff.staff_new_conversation
subscription.subscription_request
survey.survey_derivation_reminder
survey.survey_practice_reminder
user.user_appointment_request
user.user_forgot_password
user.user_invitation
user.user_password_change
user.user_patient_invitation
user.user_registration
user.user_reminder'

while getopts W:e: opt; do
    case ${opt} in
        W)
            workers=${OPTARG}
        ;;
        e)
            environment=${OPTARG}
        ;;
     esac
done;

cat <<PART
# script generated $(date) for $environment
class monitoring::workers::$environment {
PART

for worker in $workers; do
    fullname=$environment$join$prefix$join$worker
    match=$environment$join*$worker$

    cat <<PART
  monit::monitor { '$fullname':
    name         => '$fullname',
    uid          => '$uid',
    gid          => '$gid',
    start_script => "/bin/bash -c 'APP_ENV=$environment /usr/bin/php /var/www/sm/$environment/current/public/index.php gearman worker execute $worker'",
    stop_script  => '/usr/bin/pkill -f $worker',
    matching     => '$match'
  }
PART
done

cat <<PART
}

PART
